from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib import colors
from io import BytesIO
from datetime import datetime


def generate_pdf(narrative, case_id: str) -> bytes:
    """Generate a PDF report from a SAR narrative."""
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        topMargin=2 * cm, bottomMargin=2 * cm,
        leftMargin=2.5 * cm, rightMargin=2.5 * cm,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "SARTitle", parent=styles["Title"],
        fontSize=16, spaceAfter=20,
    )
    heading_style = ParagraphStyle(
        "SARHeading", parent=styles["Heading2"],
        fontSize=12, textColor=colors.HexColor("#1a237e"), spaceAfter=10,
    )
    body_style = ParagraphStyle(
        "SARBody", parent=styles["BodyText"],
        fontSize=10, leading=14, spaceAfter=8,
    )
    meta_style = ParagraphStyle(
        "SARMeta", parent=styles["BodyText"],
        fontSize=8, textColor=colors.grey, spaceAfter=4,
    )

    story = []

    # Header
    story.append(Paragraph("SUSPICIOUS TRANSACTION REPORT", title_style))
    story.append(Paragraph("Case ID: %s" % case_id, meta_style))
    story.append(Paragraph(
        "Generated: %s" % datetime.now().strftime("%Y-%m-%d %H:%M:%S"), meta_style
    ))
    story.append(Paragraph("Classification: CONFIDENTIAL", meta_style))
    story.append(Spacer(1, 20))

    # Narrative text
    if hasattr(narrative, "narrative_text"):
        text = narrative.narrative_text
    else:
        text = str(narrative)

    for line in text.split("\n"):
        line = line.strip()
        if not line:
            story.append(Spacer(1, 6))
        elif any(line.startswith(prefix) for prefix in ("I.", "II.", "III.", "IV.", "V.")):
            story.append(Paragraph(line, heading_style))
        else:
            line = line.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            story.append(Paragraph(line, body_style))

    # Footer
    story.append(Spacer(1, 30))
    story.append(Paragraph("--- END OF REPORT ---", meta_style))
    story.append(Paragraph(
        "This report was generated by AuditWatch SAR Narrative Generator.", meta_style
    ))
    story.append(Paragraph(
        "All data points are traceable via the audit trail.", meta_style
    ))

    doc.build(story)
    return buffer.getvalue()
